name: Build

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        
    - name: Create "out" directory
      run: mkdir out
      
    - name: make
      run: mingw32-make uberforcer_windows
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Uberforcer_x86
        path: out\uberforcer.exe
